# -*- coding: utf-8 -*-
"""
/***************************************************************************
 S2_vn_rectangle
                                 A QGIS plugin
 Sentinel 2 removed cloud
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-11
        copyright            : (C) 2020 by GFD
        email                : hoa.lq@gfd.com.vn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load S2_vn_rectangle class from file S2_vn_rectangle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sentinel2_removed_cloud_rec import S2_vn_rectangle
    return S2_vn_rectangle(iface)
